Fix/settings font
praekeltfoundation/gem-bbb-indo pull request #144
Opened 2016-11-28 10:29 UTC by tjizep

2016-11-28 16:41 UTC, wscheffer requested changes

2016-11-28 16:41 UTC, wscheffer commented on app/src/main/java/org/gem/indo/dooit/views/settings/SettingsActivity.java
> +public class SettingsActivity extends DooitActivity {
I don't see any Font changes in this PR?

2016-11-29 04:44 UTC, wvictor-rr commented on app/src/main/java/org/gem/indo/dooit/views/settings/SettingsActivity.java
> +public class SettingsActivity extends DooitActivity {
`fontPath` was not working because the settings activity did not inherit from DooitActivity, so the Calligraphy context wrapper wasn't being set up.

2016-11-29 04:45 UTC, wvictor-rr approved these changes

2016-11-29 04:46 UTC, merged