Fix/load remote image
praekeltfoundation/gem-bbb-indo pull request #145
Opened 2016-11-28 13:08 UTC by tjizep

2016-11-28 15:21 UTC, wscheffer requested changes

2016-11-28 15:21 UTC, wscheffer commented on app/src/main/java/org/gem/indo/dooit/views/helpers/activity/CurrencyHelper.java
> +            return NumberFormat.getCurrencyInstance().format(number);
Why use BigDecimal and not 
` return NumberFormat.getCurrencyInstance().format(Double.format(String.valueOf(o)))` ?

2016-11-28 15:21 UTC, wscheffer commented on app/src/main/java/org/gem/indo/dooit/views/main/MainActivity.java
> +    private class ProfileImageTask extends AsyncTask<Void,Integer,RoundedBitmapDrawable>{
Why use AsyncTask this defies the purpose of using Fresco which handles Image Streaming and Scaling. This solution  downloads this image every time and does not use Fresco Image Cache ?

2016-11-29 05:03 UTC, wvictor-rr commented
Replaced by https://github.com/praekeltfoundation/gem-bbb-indo/pull/148

2016-11-29 05:03 UTC, closed without merging