Fix/webview t and c
praekeltfoundation/gem-bbb-indo pull request #149
Opened 2016-11-29 10:46 UTC by tjizep

2016-11-29 13:46 UTC, wscheffer requested changes

2016-11-29 13:46 UTC, wscheffer commented on app/src/main/res/layout/activity_onboarding_web_view.xml
> +        <android.support.design.widget.CollapsingToolbarLayout
Why add CollapsingToolbarLayout?

2016-11-29 13:46 UTC, wscheffer commented on app/src/main/java/org/gem/indo/dooit/views/onboarding/OnboardingWebActivity.java
>  import android.net.NetworkInfo;
Why do we have Two WebView Activities?

2016-12-01 04:51 UTC, wvictor-rr commented on app/src/staging/java/org/gem/indo/dooit/Constants.java
> +    public static final String BASE_URL = "http://10.0.2.2:8000";
Please don't commit the Constants file pointing to the local dev server.

2016-12-01 05:03 UTC, wvictor-rr commented on app/src/main/java/org/gem/indo/dooit/views/onboarding/OnboardingWebActivity.java
>  import android.net.NetworkInfo;
This was my doing. Will be fixed in https://github.com/praekeltfoundation/gem-bbb-indo/pull/163

2016-12-01 05:07 UTC, wvictor-rr commented on app/src/main/res/layout/activity_onboarding_web_view.xml
> +        <android.support.design.widget.CollapsingToolbarLayout
We were trying something out in order to match the designs. We'll change this to a normal toolbar in https://github.com/praekeltfoundation/gem-bbb-indo/pull/163

2016-12-01 05:07 UTC, merged