Bugfix/registration email
praekeltfoundation/gem-bbb-indo pull request #305
Opened 2016-12-21 07:21 UTC by FredJEhlers

2016-12-21 07:21 UTC, FredJEhlers commented
This is to be merged after PR #272

2016-12-21 14:18 UTC, FredJEhlers commented
#135 has been solved in this PR as well

2016-12-22 04:57 UTC, wvictor-rr requested changes
The hint text on the username field must be changed to `Example: Bina124`

See issue https://github.com/praekeltfoundation/gem-bbb-indo/issues/275

2016-12-23 08:05 UTC, wvictor-rr approved these changes
Think everything is working pretty well now. Thanks @FredJEhlers

2016-12-23 08:05 UTC, wvictor-rr commented on app/src/main/res/values/strings.xml
> +    <string name="reg_options">You can use your email or mobile number or both to register</string>
This string **must** be in the Indonesian `strings.xml` file as well, even if it has English content. A mismatch between the string files is a hard error when deploying a release build.

2016-12-23 08:05 UTC, wvictor-rr commented on app/src/main/java/org/gem/indo/dooit/views/main/fragments/target/TargetFragment.java
> +                                showGoals(goals.get(0).getTimeIsUp());
This is not correct. `showGoals` is called when the goals are done downloading. If the first Goal is missed, the text is set to visible and stays visible when scrolling between Goals.

The visible/invisible conditional needs to be moved to the `populateGoal` method, since that is called each time the user navigates a Goal

2016-12-23 08:05 UTC, wvictor-rr commented on app/src/main/java/org/gem/indo/dooit/views/main/fragments/target/TargetFragment.java
> +        if(today.after(endOfGoalDate))
Move this conditional into the Goal model class. It is business logic that should preferably be reusable.

2016-12-23 08:05 UTC, wvictor-rr commented on app/src/main/java/org/gem/indo/dooit/models/goal/Goal.java
> +    private boolean timeIsUp;
Remove this field and determine the boolean programatically in a method. This field is currently not in the model on the server, and there is nothing ensuring the integrity between this field, the current datetime and the Goal's `endDate`.

eg.

```java
public boolean isMissed() {
      return new Date().after(endDate.toDate());
}
```

2016-12-23 08:12 UTC, merged