Nav arrows only show when their is more than one goal
praekeltfoundation/gem-bbb-indo pull request #428
Opened 2017-01-13 14:36 UTC by ChadGarrett

Fixes #426 

When there is only one goal, no nav arrows will be displayed

2017-01-16 07:13 UTC, wvictor-rr requested changes
Please change

2017-01-16 07:15 UTC, wvictor-rr requested changes

2017-01-16 07:15 UTC, wvictor-rr commented on app/src/main/java/org/gem/indo/dooit/views/main/fragments/target/TargetFragment.java
> +    private void updateScrollImages() {
@ChadGarrett Rename this method to something more fitting, like `updateNavButtons` or `updateNavCarets`. **"Images"** makes it seem like it has something to do with the Goal images.

2017-01-17 06:03 UTC, ChadGarrett commented
Requested changes made @wvictor-rr

2017-01-19 05:49 UTC, wvictor-rr approved these changes

2017-01-19 06:00 UTC, merged