Tip search and article view
praekeltfoundation/gem-bbb-indo pull request #88
Opened 2016-11-13 10:00 UTC by wvictor-rr

2016-11-13 17:37 UTC, wscheffer requested changes

2016-11-13 17:37 UTC, wscheffer commented on app/src/main/java/com/nike/dooit/views/main/fragments/TipsFragment.java
>      private static final String TAG = "TipArchive";
TAGs are usually set to TipsFragment.class.getName()

2016-11-13 17:37 UTC, wscheffer commented on app/src/main/java/com/nike/dooit/views/main/fragments/TipsFragment.java
> +                        String.format("Opening '%s'", tip.getTitle()), Toast.LENGTH_SHORT).show();
Should be declared as a String Resource for Local

2016-11-13 17:37 UTC, wscheffer commented on app/src/main/java/com/nike/dooit/views/main/fragments/tip/TipViewHolder.java
> +        Toast.makeText(view.getContext(),
Should be declared as a String Resource for Local

2016-11-14 14:29 UTC, wvictor-rr commented on app/src/main/java/com/nike/dooit/views/main/fragments/tip/TipViewHolder.java
> +        Toast.makeText(view.getContext(),
Done

2016-11-15 10:48 UTC, merged